// flow-typed signature: cfe3a7bad188b2e70baeccc376ef5f80
// flow-typed version: <<STUB>>/material-ui-pickers_v1.0.0-rc.17/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-pickers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-pickers/_helpers/date-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_helpers/time-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/BasePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/DateTextField' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/MaskedInput' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/ModalDialog' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/PickerToolbar' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/ToolbarButton' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/_shared/WithUtils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/clock-types' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/date-picker-view' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/constants/prop-types' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/Calendar' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/CalendarHeader' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/Day' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/DayWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/SlideTransition' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/Year' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/components/YearSelection' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePickerInline' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/DatePickerModal' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DatePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerHeader' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerTabs' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerInline' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/DateTimePickerModal' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/DateTimePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.cjs' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.umd' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/dist/material-ui-pickers.umd.min' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/Clock' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/ClockNumber' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/ClockNumbers' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/ClockPointer' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/components/TimePickerView' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/index' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePicker' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePickerInline' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/TimePicker/TimePickerModal' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/date-fns-utils-old' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/date-fns-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/luxon-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/moment-utils' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/utils/MuiPickersUtilsProvider' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/wrappers/InlineWrapper' {
  declare module.exports: any;
}

declare module 'material-ui-pickers/wrappers/ModalWrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-pickers/_helpers/date-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/date-utils'>;
}
declare module 'material-ui-pickers/_helpers/time-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_helpers/time-utils'>;
}
declare module 'material-ui-pickers/_shared/BasePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/BasePicker'>;
}
declare module 'material-ui-pickers/_shared/DateTextField.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/DateTextField'>;
}
declare module 'material-ui-pickers/_shared/MaskedInput.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/MaskedInput'>;
}
declare module 'material-ui-pickers/_shared/ModalDialog.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/ModalDialog'>;
}
declare module 'material-ui-pickers/_shared/PickerToolbar.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/PickerToolbar'>;
}
declare module 'material-ui-pickers/_shared/ToolbarButton.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/ToolbarButton'>;
}
declare module 'material-ui-pickers/_shared/WithUtils.js' {
  declare module.exports: $Exports<'material-ui-pickers/_shared/WithUtils'>;
}
declare module 'material-ui-pickers/constants/clock-types.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/clock-types'>;
}
declare module 'material-ui-pickers/constants/date-picker-view.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/date-picker-view'>;
}
declare module 'material-ui-pickers/constants/prop-types.js' {
  declare module.exports: $Exports<'material-ui-pickers/constants/prop-types'>;
}
declare module 'material-ui-pickers/DatePicker/components/Calendar.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/Calendar'>;
}
declare module 'material-ui-pickers/DatePicker/components/CalendarHeader.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/CalendarHeader'>;
}
declare module 'material-ui-pickers/DatePicker/components/Day.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/Day'>;
}
declare module 'material-ui-pickers/DatePicker/components/DayWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/DayWrapper'>;
}
declare module 'material-ui-pickers/DatePicker/components/SlideTransition.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/SlideTransition'>;
}
declare module 'material-ui-pickers/DatePicker/components/Year.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/Year'>;
}
declare module 'material-ui-pickers/DatePicker/components/YearSelection.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/components/YearSelection'>;
}
declare module 'material-ui-pickers/DatePicker/DatePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePicker'>;
}
declare module 'material-ui-pickers/DatePicker/DatePickerInline.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePickerInline'>;
}
declare module 'material-ui-pickers/DatePicker/DatePickerModal.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/DatePickerModal'>;
}
declare module 'material-ui-pickers/DatePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/DatePicker/index'>;
}
declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerHeader.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/components/DateTimePickerHeader'>;
}
declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerTabs.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/components/DateTimePickerTabs'>;
}
declare module 'material-ui-pickers/DateTimePicker/components/DateTimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/components/DateTimePickerView'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePicker'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerInline.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerInline'>;
}
declare module 'material-ui-pickers/DateTimePicker/DateTimePickerModal.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/DateTimePickerModal'>;
}
declare module 'material-ui-pickers/DateTimePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/DateTimePicker/index'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.cjs.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.cjs'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.umd.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.umd'>;
}
declare module 'material-ui-pickers/dist/material-ui-pickers.umd.min.js' {
  declare module.exports: $Exports<'material-ui-pickers/dist/material-ui-pickers.umd.min'>;
}
declare module 'material-ui-pickers/index' {
  declare module.exports: $Exports<'material-ui-pickers'>;
}
declare module 'material-ui-pickers/index.js' {
  declare module.exports: $Exports<'material-ui-pickers'>;
}
declare module 'material-ui-pickers/TimePicker/components/Clock.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/Clock'>;
}
declare module 'material-ui-pickers/TimePicker/components/ClockNumber.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/ClockNumber'>;
}
declare module 'material-ui-pickers/TimePicker/components/ClockNumbers.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/ClockNumbers'>;
}
declare module 'material-ui-pickers/TimePicker/components/ClockPointer.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/ClockPointer'>;
}
declare module 'material-ui-pickers/TimePicker/components/TimePickerView.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/components/TimePickerView'>;
}
declare module 'material-ui-pickers/TimePicker/index.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/index'>;
}
declare module 'material-ui-pickers/TimePicker/TimePicker.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePicker'>;
}
declare module 'material-ui-pickers/TimePicker/TimePickerInline.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePickerInline'>;
}
declare module 'material-ui-pickers/TimePicker/TimePickerModal.js' {
  declare module.exports: $Exports<'material-ui-pickers/TimePicker/TimePickerModal'>;
}
declare module 'material-ui-pickers/utils/date-fns-utils-old.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/date-fns-utils-old'>;
}
declare module 'material-ui-pickers/utils/date-fns-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/date-fns-utils'>;
}
declare module 'material-ui-pickers/utils/luxon-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/luxon-utils'>;
}
declare module 'material-ui-pickers/utils/moment-utils.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/moment-utils'>;
}
declare module 'material-ui-pickers/utils/MuiPickersUtilsProvider.js' {
  declare module.exports: $Exports<'material-ui-pickers/utils/MuiPickersUtilsProvider'>;
}
declare module 'material-ui-pickers/wrappers/InlineWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/wrappers/InlineWrapper'>;
}
declare module 'material-ui-pickers/wrappers/ModalWrapper.js' {
  declare module.exports: $Exports<'material-ui-pickers/wrappers/ModalWrapper'>;
}
