// flow-typed signature: b64674c50cb76cc6e261ef7038a02fb3
// flow-typed version: <<STUB>>/@material-ui/pickers_v^3.2.2/flow_v0.105.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/pickers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/pickers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/pickers/_helpers/date-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_helpers/text-field-helper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_helpers/time-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_helpers/utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useIsLandscape' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useKeyboardPickerState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useKeyDown' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useOpenState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/usePickerState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useStaticState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useUtils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/hooks/useViews' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/ArrowLeftIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/ArrowRightIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/DateRangeIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/KeyboardIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/icons/TimeIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/KeyboardDateInput' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/ModalDialog' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/PickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/PureDateInput' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/ToolbarButton' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/ToolbarText' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/_shared/WithUtils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/constants/ClockType' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/constants/dimensions' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/constants/prop-types' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker/DatePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker/DateTimePickerTabs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker/DateTimePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.esm' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.umd' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/dist/material-ui-pickers.umd.min' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/_helpers/date-utils.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/_helpers/text-field-helper.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/_shared/ModalDialog.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/DatePicker/Calendar.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/DatePicker/Month.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/DatePicker/MonthSelection.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/commands' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/DatePicker.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/DatePickerProps.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/DatePickerRoot.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/DateTimePicker.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/DateTimePickerRoot.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/KeyboardDatePicker.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/KeyboardDateTimePicker.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/Theme.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/e2e/TimePicker.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/MuiPickersUtilsProvider.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/test-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/__tests__/TimePicker/Clock.test' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_helpers/date-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_helpers/text-field-helper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_helpers/time-utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_helpers/utils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useIsLandscape' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useKeyboardPickerState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useKeyDown' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useOpenState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/usePickerState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useStaticState' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useUtils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/hooks/useViews' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/icons/ArrowLeftIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/icons/ArrowRightIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/icons/DateRangeIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/icons/KeyboardIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/icons/TimeIcon' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/KeyboardDateInput' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/ModalDialog' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/PickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/PureDateInput' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/ToolbarButton' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/ToolbarText' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/_shared/WithUtils' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/constants/ClockType' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/constants/dimensions' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/constants/prop-types' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DatePicker/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DatePicker/DatePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DatePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DateTimePicker/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DateTimePicker/DateTimePickerTabs' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DateTimePicker/DateTimePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/DateTimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/MuiPickersUtilsProvider' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Picker/Picker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Picker/WrappedKeyboardPicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/Picker/WrappedPurePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/TimePicker/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/TimePicker/TimePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/typings/BasePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/typings/date' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/typings/extendMui' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/typings/overrides' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Calendar/Calendar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Calendar/Day' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Calendar/DayWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Calendar/SlideTransition' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Clock/Clock' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Clock/ClockNumber' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Clock/ClockNumbers' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Clock/ClockPointer' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Clock/ClockView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Month/Month' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Month/MonthView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Year/Year' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/views/Year/YearView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/wrappers/InlineWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/wrappers/ModalWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/wrappers/StaticWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/esm/wrappers/Wrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/MuiPickersUtilsProvider' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker/Picker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker/WrappedKeyboardPicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/Picker/WrappedPurePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker/TimePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/TimePicker/TimePickerToolbar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/BasePicker' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/date' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/extendMui' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/typings/overrides' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/Calendar' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/Day' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/DayWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Calendar/SlideTransition' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/Clock' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockNumber' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockNumbers' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockPointer' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Clock/ClockView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Month/Month' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Month/MonthView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Year/Year' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/views/Year/YearView' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/InlineWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/ModalWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/StaticWrapper' {
  declare module.exports: any;
}

declare module '@material-ui/pickers/wrappers/Wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/pickers/_helpers/date-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/date-utils'>;
}
declare module '@material-ui/pickers/_helpers/text-field-helper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/text-field-helper'>;
}
declare module '@material-ui/pickers/_helpers/time-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/time-utils'>;
}
declare module '@material-ui/pickers/_helpers/utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_helpers/utils'>;
}
declare module '@material-ui/pickers/_shared/hooks/useIsLandscape.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useIsLandscape'>;
}
declare module '@material-ui/pickers/_shared/hooks/useKeyboardPickerState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useKeyboardPickerState'>;
}
declare module '@material-ui/pickers/_shared/hooks/useKeyDown.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useKeyDown'>;
}
declare module '@material-ui/pickers/_shared/hooks/useOpenState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useOpenState'>;
}
declare module '@material-ui/pickers/_shared/hooks/usePickerState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/usePickerState'>;
}
declare module '@material-ui/pickers/_shared/hooks/useStaticState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useStaticState'>;
}
declare module '@material-ui/pickers/_shared/hooks/useUtils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useUtils'>;
}
declare module '@material-ui/pickers/_shared/hooks/useViews.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/hooks/useViews'>;
}
declare module '@material-ui/pickers/_shared/icons/ArrowLeftIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/ArrowLeftIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/ArrowRightIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/ArrowRightIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/DateRangeIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/DateRangeIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/KeyboardIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/KeyboardIcon'>;
}
declare module '@material-ui/pickers/_shared/icons/TimeIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/icons/TimeIcon'>;
}
declare module '@material-ui/pickers/_shared/KeyboardDateInput.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/KeyboardDateInput'>;
}
declare module '@material-ui/pickers/_shared/ModalDialog.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/ModalDialog'>;
}
declare module '@material-ui/pickers/_shared/PickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/PickerToolbar'>;
}
declare module '@material-ui/pickers/_shared/PureDateInput.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/PureDateInput'>;
}
declare module '@material-ui/pickers/_shared/ToolbarButton.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/ToolbarButton'>;
}
declare module '@material-ui/pickers/_shared/ToolbarText.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/ToolbarText'>;
}
declare module '@material-ui/pickers/_shared/WithUtils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/_shared/WithUtils'>;
}
declare module '@material-ui/pickers/constants/ClockType.js' {
  declare module.exports: $Exports<'@material-ui/pickers/constants/ClockType'>;
}
declare module '@material-ui/pickers/constants/dimensions.js' {
  declare module.exports: $Exports<'@material-ui/pickers/constants/dimensions'>;
}
declare module '@material-ui/pickers/constants/prop-types.js' {
  declare module.exports: $Exports<'@material-ui/pickers/constants/prop-types'>;
}
declare module '@material-ui/pickers/DatePicker/DatePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker/DatePicker'>;
}
declare module '@material-ui/pickers/DatePicker/DatePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker/DatePickerToolbar'>;
}
declare module '@material-ui/pickers/DatePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker'>;
}
declare module '@material-ui/pickers/DatePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DatePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker/DateTimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker/DateTimePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker/DateTimePickerTabs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker/DateTimePickerTabs'>;
}
declare module '@material-ui/pickers/DateTimePicker/DateTimePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker/DateTimePickerToolbar'>;
}
declare module '@material-ui/pickers/DateTimePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker'>;
}
declare module '@material-ui/pickers/DateTimePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/DateTimePicker'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.esm.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.esm'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.umd.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.umd'>;
}
declare module '@material-ui/pickers/dist/material-ui-pickers.umd.min.js' {
  declare module.exports: $Exports<'@material-ui/pickers/dist/material-ui-pickers.umd.min'>;
}
declare module '@material-ui/pickers/esm/__tests__/_helpers/date-utils.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/_helpers/date-utils.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/_helpers/text-field-helper.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/_helpers/text-field-helper.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/_shared/ModalDialog.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/_shared/ModalDialog.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/DatePicker/Calendar.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/DatePicker/Calendar.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/DatePicker/Month.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/DatePicker/Month.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/DatePicker/MonthSelection.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/DatePicker/MonthSelection.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/commands.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/commands'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/DatePicker.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/DatePicker.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/DatePickerProps.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/DatePickerProps.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/DatePickerRoot.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/DatePickerRoot.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/DateTimePicker.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/DateTimePicker.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/DateTimePickerRoot.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/DateTimePickerRoot.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/KeyboardDatePicker.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/KeyboardDatePicker.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/KeyboardDateTimePicker.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/KeyboardDateTimePicker.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/Theme.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/Theme.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/e2e/TimePicker.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/e2e/TimePicker.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/MuiPickersUtilsProvider.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/MuiPickersUtilsProvider.test'>;
}
declare module '@material-ui/pickers/esm/__tests__/test-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/test-utils'>;
}
declare module '@material-ui/pickers/esm/__tests__/TimePicker/Clock.test.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/__tests__/TimePicker/Clock.test'>;
}
declare module '@material-ui/pickers/esm/_helpers/date-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_helpers/date-utils'>;
}
declare module '@material-ui/pickers/esm/_helpers/text-field-helper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_helpers/text-field-helper'>;
}
declare module '@material-ui/pickers/esm/_helpers/time-utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_helpers/time-utils'>;
}
declare module '@material-ui/pickers/esm/_helpers/utils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_helpers/utils'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useIsLandscape.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useIsLandscape'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useKeyboardPickerState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useKeyboardPickerState'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useKeyDown.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useKeyDown'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useOpenState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useOpenState'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/usePickerState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/usePickerState'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useStaticState.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useStaticState'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useUtils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useUtils'>;
}
declare module '@material-ui/pickers/esm/_shared/hooks/useViews.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/hooks/useViews'>;
}
declare module '@material-ui/pickers/esm/_shared/icons/ArrowLeftIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/icons/ArrowLeftIcon'>;
}
declare module '@material-ui/pickers/esm/_shared/icons/ArrowRightIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/icons/ArrowRightIcon'>;
}
declare module '@material-ui/pickers/esm/_shared/icons/DateRangeIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/icons/DateRangeIcon'>;
}
declare module '@material-ui/pickers/esm/_shared/icons/KeyboardIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/icons/KeyboardIcon'>;
}
declare module '@material-ui/pickers/esm/_shared/icons/TimeIcon.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/icons/TimeIcon'>;
}
declare module '@material-ui/pickers/esm/_shared/KeyboardDateInput.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/KeyboardDateInput'>;
}
declare module '@material-ui/pickers/esm/_shared/ModalDialog.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/ModalDialog'>;
}
declare module '@material-ui/pickers/esm/_shared/PickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/PickerToolbar'>;
}
declare module '@material-ui/pickers/esm/_shared/PureDateInput.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/PureDateInput'>;
}
declare module '@material-ui/pickers/esm/_shared/ToolbarButton.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/ToolbarButton'>;
}
declare module '@material-ui/pickers/esm/_shared/ToolbarText.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/ToolbarText'>;
}
declare module '@material-ui/pickers/esm/_shared/WithUtils.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/_shared/WithUtils'>;
}
declare module '@material-ui/pickers/esm/constants/ClockType.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/constants/ClockType'>;
}
declare module '@material-ui/pickers/esm/constants/dimensions.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/constants/dimensions'>;
}
declare module '@material-ui/pickers/esm/constants/prop-types.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/constants/prop-types'>;
}
declare module '@material-ui/pickers/esm/DatePicker/DatePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DatePicker/DatePicker'>;
}
declare module '@material-ui/pickers/esm/DatePicker/DatePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DatePicker/DatePickerToolbar'>;
}
declare module '@material-ui/pickers/esm/DatePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DatePicker'>;
}
declare module '@material-ui/pickers/esm/DatePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DatePicker'>;
}
declare module '@material-ui/pickers/esm/DateTimePicker/DateTimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DateTimePicker/DateTimePicker'>;
}
declare module '@material-ui/pickers/esm/DateTimePicker/DateTimePickerTabs.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DateTimePicker/DateTimePickerTabs'>;
}
declare module '@material-ui/pickers/esm/DateTimePicker/DateTimePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DateTimePicker/DateTimePickerToolbar'>;
}
declare module '@material-ui/pickers/esm/DateTimePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DateTimePicker'>;
}
declare module '@material-ui/pickers/esm/DateTimePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/DateTimePicker'>;
}
declare module '@material-ui/pickers/esm/index' {
  declare module.exports: $Exports<'@material-ui/pickers/esm'>;
}
declare module '@material-ui/pickers/esm/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm'>;
}
declare module '@material-ui/pickers/esm/MuiPickersUtilsProvider.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/MuiPickersUtilsProvider'>;
}
declare module '@material-ui/pickers/esm/Picker/Picker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Picker/Picker'>;
}
declare module '@material-ui/pickers/esm/Picker/WrappedKeyboardPicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Picker/WrappedKeyboardPicker'>;
}
declare module '@material-ui/pickers/esm/Picker/WrappedPurePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/Picker/WrappedPurePicker'>;
}
declare module '@material-ui/pickers/esm/TimePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/TimePicker'>;
}
declare module '@material-ui/pickers/esm/TimePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/TimePicker'>;
}
declare module '@material-ui/pickers/esm/TimePicker/TimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/TimePicker/TimePicker'>;
}
declare module '@material-ui/pickers/esm/TimePicker/TimePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/TimePicker/TimePickerToolbar'>;
}
declare module '@material-ui/pickers/esm/typings/BasePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/typings/BasePicker'>;
}
declare module '@material-ui/pickers/esm/typings/date.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/typings/date'>;
}
declare module '@material-ui/pickers/esm/typings/extendMui.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/typings/extendMui'>;
}
declare module '@material-ui/pickers/esm/typings/overrides.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/typings/overrides'>;
}
declare module '@material-ui/pickers/esm/views/Calendar/Calendar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Calendar/Calendar'>;
}
declare module '@material-ui/pickers/esm/views/Calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Calendar/CalendarHeader'>;
}
declare module '@material-ui/pickers/esm/views/Calendar/Day.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Calendar/Day'>;
}
declare module '@material-ui/pickers/esm/views/Calendar/DayWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Calendar/DayWrapper'>;
}
declare module '@material-ui/pickers/esm/views/Calendar/SlideTransition.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Calendar/SlideTransition'>;
}
declare module '@material-ui/pickers/esm/views/Clock/Clock.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Clock/Clock'>;
}
declare module '@material-ui/pickers/esm/views/Clock/ClockNumber.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Clock/ClockNumber'>;
}
declare module '@material-ui/pickers/esm/views/Clock/ClockNumbers.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Clock/ClockNumbers'>;
}
declare module '@material-ui/pickers/esm/views/Clock/ClockPointer.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Clock/ClockPointer'>;
}
declare module '@material-ui/pickers/esm/views/Clock/ClockView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Clock/ClockView'>;
}
declare module '@material-ui/pickers/esm/views/Month/Month.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Month/Month'>;
}
declare module '@material-ui/pickers/esm/views/Month/MonthView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Month/MonthView'>;
}
declare module '@material-ui/pickers/esm/views/Year/Year.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Year/Year'>;
}
declare module '@material-ui/pickers/esm/views/Year/YearView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/views/Year/YearView'>;
}
declare module '@material-ui/pickers/esm/wrappers/InlineWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/wrappers/InlineWrapper'>;
}
declare module '@material-ui/pickers/esm/wrappers/ModalWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/wrappers/ModalWrapper'>;
}
declare module '@material-ui/pickers/esm/wrappers/StaticWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/wrappers/StaticWrapper'>;
}
declare module '@material-ui/pickers/esm/wrappers/Wrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/esm/wrappers/Wrapper'>;
}
declare module '@material-ui/pickers/index' {
  declare module.exports: $Exports<'@material-ui/pickers'>;
}
declare module '@material-ui/pickers/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers'>;
}
declare module '@material-ui/pickers/MuiPickersUtilsProvider.js' {
  declare module.exports: $Exports<'@material-ui/pickers/MuiPickersUtilsProvider'>;
}
declare module '@material-ui/pickers/Picker/Picker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker/Picker'>;
}
declare module '@material-ui/pickers/Picker/WrappedKeyboardPicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker/WrappedKeyboardPicker'>;
}
declare module '@material-ui/pickers/Picker/WrappedPurePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/Picker/WrappedPurePicker'>;
}
declare module '@material-ui/pickers/TimePicker/index' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker'>;
}
declare module '@material-ui/pickers/TimePicker/index.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker'>;
}
declare module '@material-ui/pickers/TimePicker/TimePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker/TimePicker'>;
}
declare module '@material-ui/pickers/TimePicker/TimePickerToolbar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/TimePicker/TimePickerToolbar'>;
}
declare module '@material-ui/pickers/typings/BasePicker.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/BasePicker'>;
}
declare module '@material-ui/pickers/typings/date.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/date'>;
}
declare module '@material-ui/pickers/typings/extendMui.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/extendMui'>;
}
declare module '@material-ui/pickers/typings/overrides.js' {
  declare module.exports: $Exports<'@material-ui/pickers/typings/overrides'>;
}
declare module '@material-ui/pickers/views/Calendar/Calendar.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/Calendar'>;
}
declare module '@material-ui/pickers/views/Calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/CalendarHeader'>;
}
declare module '@material-ui/pickers/views/Calendar/Day.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/Day'>;
}
declare module '@material-ui/pickers/views/Calendar/DayWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/DayWrapper'>;
}
declare module '@material-ui/pickers/views/Calendar/SlideTransition.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Calendar/SlideTransition'>;
}
declare module '@material-ui/pickers/views/Clock/Clock.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/Clock'>;
}
declare module '@material-ui/pickers/views/Clock/ClockNumber.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockNumber'>;
}
declare module '@material-ui/pickers/views/Clock/ClockNumbers.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockNumbers'>;
}
declare module '@material-ui/pickers/views/Clock/ClockPointer.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockPointer'>;
}
declare module '@material-ui/pickers/views/Clock/ClockView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Clock/ClockView'>;
}
declare module '@material-ui/pickers/views/Month/Month.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Month/Month'>;
}
declare module '@material-ui/pickers/views/Month/MonthView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Month/MonthView'>;
}
declare module '@material-ui/pickers/views/Year/Year.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Year/Year'>;
}
declare module '@material-ui/pickers/views/Year/YearView.js' {
  declare module.exports: $Exports<'@material-ui/pickers/views/Year/YearView'>;
}
declare module '@material-ui/pickers/wrappers/InlineWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/InlineWrapper'>;
}
declare module '@material-ui/pickers/wrappers/ModalWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/ModalWrapper'>;
}
declare module '@material-ui/pickers/wrappers/StaticWrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/StaticWrapper'>;
}
declare module '@material-ui/pickers/wrappers/Wrapper.js' {
  declare module.exports: $Exports<'@material-ui/pickers/wrappers/Wrapper'>;
}
