// flow-typed signature: fad4aa392c0db25f9744b5336d61f828
// flow-typed version: <<STUB>>/@date-io/core_v^1.3.9/flow_v0.105.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@date-io/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@date-io/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@date-io/core/dev-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@date-io/core/dev-utils.js' {
  declare module.exports: $Exports<'@date-io/core/dev-utils'>;
}
